# Generated by Django 3.0.4 on 2020-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_auto_20200411_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'topping'},
        ),
        migrations.RenameField(
            model_name='toppings',
            old_name='toppings',
            new_name='topping',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pizza',
        ),
        migrations.AddField(
            model_name='toppings',
            name='name',
            field=models.ManyToManyField(to='Pizza.Pizza'),
        ),
    ]
