# Generated by Django 3.0.4 on 2020-04-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_auto_20200411_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppings',
            old_name='add_toppings',
            new_name='toppings',
        ),
    ]
