# Generated by Django 3.0.4 on 2020-04-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_auto_20200418_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='pizza',
        ),
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='Pizza.Pizza'),
        ),
    ]
